version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.3
    working_directory: /go/src/github.com/dnozdrin/detask
    steps:
      - checkout
      - run:
          name: "Setup Environment Variables"
          command: |
            echo "export CODECOV_TOKEN=$CODECOV_TOKEN" >> $BASH_ENV
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: "Add dependencies to current module and install them"
          command: go get -v -t -d ./...
      - run:
          name: "Make vendored copy of dependencies"
          command: go mod vendor
      - run:
          name: "Run unit tests"
          command: go test -coverprofile=coverage.txt -covermode=atomic -tags=test,unit ./...
      - run:
          name: "Build project"
          command: go build -race -o=./bin/detask -v ./cmd/detask
      - store_artifacts:
          path: /tmp/artifacts

      - codecov/upload:
          file: coverage.txt
