version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
  heroku: circleci/heroku@1.0.1
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: circleci
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.3
      - image: postgres:12.3-alpine
        environment:
          POSTGRES_DB: $DB_NAME
          POSTGRES_PASSWORD: $DB_PASS
    working_directory: /go/src/github.com/dnozdrin/detask
    steps:
      - checkout
      - run:
          name: "Setup Environment Variables"
          command: |
            echo "export CODECOV_TOKEN=$CODECOV_TOKEN" >> $BASH_ENV
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: "Waiting for Postgres to be ready"
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: "Add dependencies to current module and install them"
          command: go get -v -t -d ./...
      - run:
          name: "Make vendored copy of dependencies"
          command: go mod vendor
      - run:
          name: "Run unit tests"
          command: go test -coverprofile=coverage.txt -covermode=atomic -tags=test,unit ./...
      - run:
          name: "Run end-to-end tests"
          command: go test -coverpkg=./... -coverprofile=coverage.http.txt -tags=test,integrational ./test
      - run:
          name: "Merge tests coverage stats"
          command: tail -n +2 coverage.http.txt >> coverage.txt
      - run:
          name: "Build project"
          command: go build -race -o=./bin/detask -v ./cmd/detask
      - store_artifacts:
          path: /tmp/artifacts

      - codecov/upload:
          file: coverage.txt
